#include <stdio.h> 
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <sys/types.h> 
#include <sys/socket.h>
#include <netinet/in.h>

#include <netdb.h>

#include <sys/wait.h> // fork()
#include <errno.h>
#include <signal.h>  // Used for handling SIGINT (ctrl+c)
#include <sys/mman.h>
#include <pthread.h> // pthread functions & data for parallelism

/* 
   Client Side Specifications:

   1. Prompt the user for their username and password
   2. Provide a welcome message that displays number of new messages
   3. Provide a menu for the user to select valid options. Should be a way to navigate back
   4. Menu option: See Offline Messages
   5. Menu option: Edit Subscriptions
   6. Menu option: Post a message
   7. Menu option: Logout
   8. Display messages in realtime
   9. Menu option: hashtag search (get last 10 hashtags generated by any of the user's subscriptions)

*/

// Specifies error messages and ends program
void error(const char *msg)
{
  perror(msg);
  exit(1);
}

int main(int argc, char *argv[])
{
  // Set up variables for sockets
  int sockfd;            // Socket file descriptor
  int portno = 7158;     // Port #
  char snd_buffer[256];  // Buffer to send messages
  char rcv_buffer[256];  // Buffer to receive messsages

  int* log_out = mmap(NULL, sizeof(log_out), PROT_READ | PROT_WRITE, 
       MAP_SHARED | MAP_ANONYMOUS, -1, 0);

  struct sockaddr_in serv_addr; // Holds address of server socket
  struct hostent *server = gethostbyname( "localhost" ); // Holds hostname of server
  int n;

  sockfd = socket(AF_INET, SOCK_STREAM, 0);  // Create a new TCP socket
  if (sockfd < 0)
  {
    close(sockfd);
    error("ERROR opening socket");
  }

  bzero((char *) &serv_addr, sizeof(serv_addr)); // Clear struct
  serv_addr.sin_family = AF_INET;                // Specify internet domain
  bcopy((char *)server->h_addr,                  // Specify server hostname
	(char *)&serv_addr.sin_addr.s_addr,
	server->h_length);
  serv_addr.sin_port = htons(portno);            // Specify port #



  // Connect to server
  if (connect(sockfd,(struct sockaddr *) &serv_addr,sizeof(serv_addr)) < 0) 
  {
    close(sockfd);
    error("ERROR connecting");
  }

  pid_t pid = fork();
  for( ;; )
  {
    if ( pid < 0 )
    {
      error("fork()");
      //don't go here!
      continue;
    }
    else if(pid == 0) // Child/Client process
    {
      // Get response from server
      bzero(rcv_buffer,256);
      n = read(sockfd,rcv_buffer,255);
      if (n < 0) 
      {
	close(sockfd);
	error("ERROR reading from socket");
      }
    
      // If logged out, confirm message
      if( strncmp(rcv_buffer,"Logged out successfully.",24) == 0 )
      {
	printf("%s\n", rcv_buffer );
	*log_out = 1; // Tell server to exit as well
	exit(0);
	break;
      }
      else
	printf("%s", rcv_buffer );
      fflush(stdout);
    } /* child process */

    else if(pid > 0) // Parent/Server process
    {
      if( *log_out == 1 )
      {
	exit(0);
      }

      // Get message from user
      bzero(snd_buffer,256);
      fgets(snd_buffer,255,stdin);
      
      // Send to server
      n = write(sockfd,snd_buffer,strlen(snd_buffer));
      if (n < 0) 
      {
	close(sockfd);
	error("ERROR writing to socket");
      } 
      fflush(stdout);

    } /* parent process */

  } /* for( ;; ) */
  close(sockfd);
  return 0; 

}
