#include <stdio.h> 
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <sys/types.h> 
#include <sys/socket.h>
#include <netinet/in.h>

#include <netdb.h>

#include <sys/wait.h> // fork()
#include <errno.h>

/* 
   Client Side Specifications:

   1. Prompt the user for their username and password
   2. Provide a welcome message that displays number of new messages
   3. Provide a menu for the user to select valid options. Should be a way to navigate back
   4. Menu option: See Offline Messages
   5. Menu option: Edit Subscriptions
   6. Menu option: Post a message
   7. Menu option: Logout
   8. Display messages in realtime
   9. Menu option: hashtag search (get last 10 hashtags generated by any of the user's subscriptions)

*/

// Specifies error messages and ends program
void error(const char *msg)
{
  perror(msg);
  exit(1);
}

int main(int argc, char *argv[])
{
  // Set up variables for sockets
  int sockfd;            // Socket file descriptor
  int portno = 7158;     // Port #
  char buffer[256];      // Buffer to hold messages

  struct sockaddr_in serv_addr; // Holds address of server socket
  struct hostent *server = gethostbyname( "localhost" ); // Holds hostname of server
  int n;

  sockfd = socket(AF_INET, SOCK_STREAM, 0);  // Create a new TCP socket
  if (sockfd < 0)
  {
    close(sockfd);
    error("ERROR opening socket");
  }

  bzero((char *) &serv_addr, sizeof(serv_addr)); // Clear struct
  serv_addr.sin_family = AF_INET;                // Specify internet domain
  bcopy((char *)server->h_addr,                  // Specify server hostname
	(char *)&serv_addr.sin_addr.s_addr,
	server->h_length);
  serv_addr.sin_port = htons(portno);            // Specify port #



  // Connect to server
  if (connect(sockfd,(struct sockaddr *) &serv_addr,sizeof(serv_addr)) < 0) 
  {
    close(sockfd);
    error("ERROR connecting");
  }

  for( ;; )
  {

    /*

      Beginnings of forking client process for reading and writing parallely.
    pid_t pid = 0;
    for(;;)
      {
	newsockfd = accept(sockfd, (struct sockaddr *) &cli_addr, &clilen);
	printf("Accepted port!\n");
	// Fork a new process whenever a new client connects
	pid = fork();
	if ( pid < 0 )
	  {
	    error("fork()");
	    //don't go here!
	    continue;
	  }
	else if(pid > 0) // Parent/Server process
	  {
	    //printf("Parent PID.\n");
	    continue;
	  }
	else if(pid == 0) // Child/Client process
	  {

	    */


    // Get response from server
    bzero(buffer,256);
    n = read(sockfd,buffer,255);
    if (n < 0) 
    {
      close(sockfd);
      error("ERROR reading from socket");
    }

    // If logged out, confirm message
    if( strncmp(buffer,"Logged out successfully.",24) == 0 )
    {
      printf("%s\n", buffer );
      break;
    }
    else
      printf("%s",buffer );
    
    // Get message from user
    //printf("message: ");
    bzero(buffer,256);
    fgets(buffer,255,stdin);

    // Send to server
    n = write(sockfd,buffer,strlen(buffer));
    if (n < 0) 
      {
	close(sockfd);
	error("ERROR writing to socket");
      }


  }

  close(sockfd);
  return 0; 

}
