#include <stdio.h> 
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <sys/types.h> 
#include <sys/socket.h>
#include <netinet/in.h>

#include <netdb.h>


/* 
   Client Side Specifications:

   1. Prompt the user for their username and password
   2. Provide a welcome message that displays number of new messages
   3. Provide a menu for the user to select valid options. Should be a way to navigate back
   4. Menu option: See Offline Messages
   5. Menu option: Edit Subscriptions
   6. Menu option: Post a message
   7. Menu option: Logout
   8. Display messages in realtime
   9. Menu option: hashtag search (get last 10 hashtags generated by any of the user's subscriptions)

*/

// Specifies error messages and ends program
void error(const char *msg)
{
  perror(msg);
  exit(1);
}

int main(int argc, char *argv[])
{
  // Set up variables for sockets
  int sockfd;            // Socket file descriptor
  int portno = 7158;     // Port #
  char buffer[256];      // Buffer to hold messages

  struct sockaddr_in serv_addr; // Holds address of server socket
  struct hostent *server = gethostbyname( "localhost" ); // Holds hostname of server
  int n;

  sockfd = socket(AF_INET, SOCK_STREAM, 0);  // Create a new TCP socket
  if (sockfd < 0)
  {
    close(sockfd);
    error("ERROR opening socket");
  }

  bzero((char *) &serv_addr, sizeof(serv_addr)); // Clear struct
  serv_addr.sin_family = AF_INET;                // Specify internet domain
  bcopy((char *)server->h_addr,                  // Specify server hostname
	(char *)&serv_addr.sin_addr.s_addr,
	server->h_length);
  serv_addr.sin_port = htons(portno);            // Specify port #

  // Connect to server
  if (connect(sockfd,(struct sockaddr *) &serv_addr,sizeof(serv_addr)) < 0) 
  {
    close(sockfd);
    error("ERROR connecting");
  }

  for( ;; )
  {
    // Get message
    printf("Please enter the message: ");
    bzero(buffer,256);
    fgets(buffer,255,stdin);

    // Send to server
    n = write(sockfd,buffer,strlen(buffer));
    if (n < 0) 
      {
	close(sockfd);
	error("ERROR writing to socket");
      }

    // Get response from server
    bzero(buffer,256);
    n = read(sockfd,buffer,255);
    if (n < 0) 
    {
      close(sockfd);
      error("ERROR reading from socket");
    }

    if( strncmp(buffer,"Logged out successfully.",24) == 0 )
    {
      printf("%s\n", buffer );
      break;
    }
    else
      printf("[Server] -  %s\n",buffer );

  }

  close(sockfd);
  return 0; 

}
