#ifndef __SERVER_H__
#define __SERVER_H__

// Macros
#define MAX_USERS 5
#define MAX_MESSAGES 255

// Declare structs
typedef struct messages_struct {
  char* from;
  char* to; // Only used for private messages
  char* message;
} message;

typedef struct user_struct {
  char* username;
  char* password;
  int   sockfd;   // The current socket the user is associated to
  message* messages;
} user;

// Declare socket descriptors
int sockfd;            // Socket file descriptor
int newsockfd;         // New socket file descriptor

// Server variables
user* users;           // List of total users
user* users_online;    // List of currently online users
int current_menu;      // Corresponds to what menu the user is in
int messagecount;      // Keeps track of number of messages received

// Error handling functions
void error(const char *msg);
void handle_signal( int signal );

// Initialization functions
user create_user( char* username, char* password, int sockfd, message* messages);
void init_users();
int is_authenticated( int* sockfd );
int authenticate_user( int* sockfd );

// Interface functions
void handle_menu( int* sockfd, int* menu );

#endif /* __SERVER_H__ */

/*   Server Side:

  1. Validate a user login (3-5 hard coded)   DONE
  2. Maintain a list of user's subscriptions to other users, and allow them to change it
  3. Receive messages and redistribute in real time
  4. Store messages sent (not delivered) if the subscribers were offline.
  5. Implement "messagecount" in order to display the number of messages received since the server was activated
*/

/*    Client Side Specifications:

   1. Prompt the user for their username and password   DONE
   2. Provide a welcome message that displays number of new messages
   3. Provide a menu for the user to select valid options. Should be a way to navigate back
   4. Menu option: See Offline Messages
   5. Menu option: Edit Subscriptions
   6. Menu option: Post a message
   7. Menu option: Logout
   8. Display messages in realtime
   9. Menu option: hashtag search (get last 10 hashtags generated by any of the user's subscriptions) */
